// Coverage matrix: renders, per jurisdiction × document × language, whether a CURRENT
// record exists, only a DEGRADED one (needs reverification), or nothing — written to
// docs/audits/coverage.md so the gaps are public and the "which state next?"
// conversation is concrete. Regenerate with `make coverage`.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadCorpus, REPO_ROOT } from "../api/corpus.ts";
import { isCurrent, DEFAULT_TODAY } from "../api/freshness.ts";
import type { ChangeType, DocumentType, Language } from "../api/types.ts";
import { pass } from "./util.ts";

const today = process.env.NAV_TODAY ?? DEFAULT_TODAY;
const corpus = loadCorpus();

const DOCS: DocumentType[] = ["court-order", "ssa-card", "drivers-license", "passport", "birth-certificate", "financial-records"];
const LANGS: Language[] = ["en", "es"];
const CHANGES: ChangeType[] = ["name", "gender-marker"];
const jurisdictions = [...new Set(corpus.map((r) => r.jurisdiction))].sort();

// One cell per jurisdiction × document × change type, so a degraded gender-marker
// record is never masked by a current name record sharing the document.
type Cell = "current" | "degraded" | "—";
function cell(j: string, d: DocumentType, c: ChangeType, l: Language): Cell {
  const records = corpus.filter(
    (r) => r.jurisdiction === j && r.document_type === d && r.language === l && r.change_type.includes(c),
  );
  if (records.length === 0) return "—";
  return records.some((r) => isCurrent(r, today)) ? "current" : "degraded";
}

const MARK: Record<Cell, string> = { current: "✅", degraded: "⚠️ degraded", "—": "—" };

let md = `# Coverage matrix

Generated by \`make coverage\` (scripts/coverage-matrix.ts) as of ${today}.
✅ = at least one current, verified record · ⚠️ degraded = records exist but all need
reverification (served with a freshness warning, never as current) · — = no records yet.

Federal rows (\`US\`) apply to every state; a state is usable when its court-order and
driver's-license rows are covered and the federal rows are current.
`;

for (const l of LANGS) {
  for (const c of CHANGES) {
    md += `\n## ${l === "en" ? "English" : "Spanish"} · ${c === "name" ? "Name change" : "Gender-marker change"}\n\n`;
    md += `| Jurisdiction | ${DOCS.join(" | ")} |\n`;
    md += `|---|${DOCS.map(() => "---").join("|")}|\n`;
    for (const j of jurisdictions) {
      md += `| ${j} | ${DOCS.map((d) => MARK[cell(j, d, c, l)]).join(" | ")} |\n`;
    }
  }
}

const counts = { current: 0, degraded: 0, missing: 0 };
for (const l of LANGS) for (const c of CHANGES) for (const j of jurisdictions) for (const d of DOCS) {
  const v = cell(j, d, c, l);
  counts[v === "—" ? "missing" : v]++;
}
md += `\n**Totals:** ${counts.current} current · ${counts.degraded} degraded · ${counts.missing} uncovered cells.\n`;

const out = join(REPO_ROOT, "docs", "audits", "coverage.md");
writeFileSync(out, md);
pass("coverage", `matrix written to docs/audits/coverage.md (${counts.current} current, ${counts.degraded} degraded, ${counts.missing} uncovered)`);
