// Launch-gate legibility gate (merge-blocking) — the same anti-drift discipline
// scripts/gate-count.ts applies to a NUMBER, applied to the OPEN REVIEW GATES.
//
// The problem: README.md and docs/STATUS.md described the open launch gates in prose that a
// human typed and a human had to remember to update. Prose drifts. "35 schema-validated
// records" sat in docs/STATUS.md while the corpus held 68 — nobody was lying, the number
// just aged. The same rot in the sentence "no record has been human-verified" would be far
// worse: it is the single most important disclosure this project makes, and the day it goes
// stale is the day the project starts overclaiming about legal guidance for a population
// that gets hurt when guidance is wrong.
//
// So the status of every launch gate is DERIVED here, from the artifacts themselves, and
// rendered into a block that README.md and docs/STATUS.md must both carry verbatim:
//
//   corpus + referrals + forms  → how many records a NAMED HUMAN has verified (it is 0)
//   scripts/source-fidelity.ts  → how many record assertions are backed by their cited source
//   corpus/source-hashes.json   → how many cited sources have no drift baseline
//   eval/gold.provenance.json   → whether the accuracy oracle is independently authored
//   docs/signoffs/*.json        → the human sign-offs that have actually happened (none)
//
// A gate can only be marked DONE by producing machine-checkable evidence. The three gates
// that need human judgement (counsel review, the screen-reader walkthrough, a real-Bedrock
// eval run) are cleared by committing a sign-off file naming a verifier who is in
// corpus/VERIFIERS.json and is NOT a placeholder — so the "Pilot Seed Reviewer" placeholder
// can never sign anything, and no one can clear a launch gate by editing a sentence.
//
//   node scripts/launch-gates.ts           # verify README + STATUS match the derived truth
//   node scripts/launch-gates.ts --write    # regenerate the block in both files

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { loadCorpus, loadVerifierRoster, isPlaceholderVerifier, REPO_ROOT } from "../api/corpus.ts";
import { loadReferrals } from "../api/referrals.ts";
import { loadForms } from "../api/forms.ts";
import { unwatchableAmong, unwatchableReason } from "../api/watchability.ts";
import { auditCorpus, loadSnapshotIndex } from "./source-fidelity.ts";
import { read, pass, fail } from "./util.ts";

const START = "<!-- launch-gates:start — GENERATED by scripts/launch-gates.ts. Do not hand-edit. -->";
const END = "<!-- launch-gates:end -->";
const TARGETS = ["README.md", "docs/STATUS.md"];

export interface LaunchGate {
  name: string;
  /** DERIVED, never typed by a human. */
  status: "OPEN" | "DONE";
  /** The machine-derived evidence, in words. */
  evidence: string;
  /** Which artifact the evidence was derived from. */
  derivedFrom: string;
}

interface SignOff {
  gate: string;
  signer: string;
  date: string;
  artifact: string;
}

/**
 * Human sign-offs, from docs/signoffs/*.json. A sign-off is only counted when its signer is
 * a REAL, named verifier in corpus/VERIFIERS.json — a placeholder cannot sign a launch gate.
 * There are none today, and the absence of the directory is the honest default.
 */
export function loadSignOffs(dir = join(REPO_ROOT, "docs", "signoffs")): SignOff[] {
  if (!existsSync(dir)) return [];
  const roster = loadVerifierRoster();
  const out: SignOff[] = [];
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".json"))) {
    const raw = JSON.parse(readFileSync(join(dir, file), "utf8")) as Partial<SignOff>;
    if (
      typeof raw.gate === "string" &&
      typeof raw.signer === "string" &&
      typeof raw.date === "string" &&
      typeof raw.artifact === "string" &&
      roster.has(raw.signer) &&
      !isPlaceholderVerifier(raw.signer, roster)
    ) {
      out.push(raw as SignOff);
    }
  }
  return out;
}

export function deriveLaunchGates(): LaunchGate[] {
  const roster = loadVerifierRoster();
  const corpus = loadCorpus();
  const referrals = loadReferrals();
  const forms = loadForms();
  const signOffs = loadSignOffs();

  // ── 1. Named-human verification ─────────────────────────────────────────────────────
  const verified = [
    ...corpus.map((r) => r.source.verifier),
    ...referrals.map((r) => r.source.verifier),
    ...forms.map((f) => f.source.verifier),
  ];
  const humanVerified = verified.filter((v) => !isPlaceholderVerifier(v, roster)).length;
  const total = verified.length;

  // ── 2. Source fidelity ──────────────────────────────────────────────────────────────
  const baseline: Record<string, string> = JSON.parse(
    readFileSync(join(REPO_ROOT, "corpus", "source-hashes.json"), "utf8"),
  ) as Record<string, string>;
  const fidelity = auditCorpus(corpus, forms, loadSnapshotIndex(), { baseline });
  const uncheckedProse = fidelity.audits.reduce((n, a) => n + a.uncheckedProse, 0);
  const totalProse = fidelity.audits.reduce((n, a) => n + a.totalSentences, 0);

  // ── 3. Drift baselines ──────────────────────────────────────────────────────────────
  // "Unwatched" is not the same as "unbaselined". A source that HAS a committed baseline but
  // that the pipeline can no longer fetch (health.ny.gov 403s our user-agent) is also
  // unwatched: source-watch reports it "unreachable (skipped)" and carries the old hash
  // forward forever, so drift there is undetectable by construction. Counting only the
  // missing baselines would have understated this by one — and that one is the New York
  // birth-certificate page, which six records depend on.
  //
  // The derivation lives in api/watchability.ts, which the RUNNING APP also reads to tell a
  // user which of the sources under their step cannot be monitored (issue #117). One
  // function, so this README row and that sentence can never disagree.
  const unwatched = unwatchableAmong([
    ...corpus.map((r) => r.source.url),
    ...forms.map((f) => f.source.url),
  ]);

  // ── 4. Gold-set independence ────────────────────────────────────────────────────────
  const provenance = JSON.parse(
    readFileSync(join(REPO_ROOT, "eval", "gold.provenance.json"), "utf8"),
  ) as { independent_author?: boolean };
  const independent = provenance.independent_author === true;

  const signed = (gate: string): SignOff | undefined => signOffs.find((s) => s.gate === gate);
  const humanGate = (gate: string, name: string): LaunchGate => {
    const s = signed(gate);
    return {
      name,
      status: s ? "DONE" : "OPEN",
      evidence: s
        ? `signed off by ${s.signer} on ${s.date} (${s.artifact})`
        : "no sign-off in `docs/signoffs/` — this gate cannot be cleared by editing a doc",
      derivedFrom: `docs/signoffs/*.json (gate: \`${gate}\`)`,
    };
  };

  return [
    {
      name: "Named-human verification of every record",
      status: humanVerified === total && total > 0 ? "DONE" : "OPEN",
      evidence: `**${humanVerified} of ${total}** records verified by a named human. ${total - humanVerified} carry the \`Pilot Seed Reviewer\` placeholder.`,
      derivedFrom: "`corpus/` + `forms/registry.json` × `corpus/VERIFIERS.json`",
    },
    {
      name: "Every record's claims backed by its own cited source",
      status: fidelity.unsupported === 0 && fidelity.uncheckable === 0 ? "DONE" : "OPEN",
      evidence:
        `${fidelity.supported} assertion(s) located in their cited source, ${fidelity.unsupported} unsupported ` +
        `(merge-blocking), **${fidelity.uncheckable} UNCHECKABLE**. Separately, **${uncheckedProse} of ${totalProse} prose ` +
        `sentences carry no checkable literal** and no gate vouches for them.`,
      derivedFrom: "`make fidelity` (`scripts/source-fidelity.ts`)",
    },
    {
      name: "Every cited source actually under drift watch",
      status: unwatched.length === 0 ? "DONE" : "OPEN",
      // The reason is per-source, and the two are not the same failure: a 403 means no
      // baseline CAN be taken without spoofing a user-agent we refuse to spoof, while a
      // missing baseline means none has been taken YET and a verifier can fix it by
      // reading the page. Reporting both as "(403)" understated one and misdescribed the
      // other — the SS-5 PDF is a forms-registry link with no reviewed baseline, not a
      // 403 (docs/STATUS.md 2026-07-13, docs/audits/data-card.md).
      evidence:
        unwatched.length === 0
          ? "every cited source and form is fetchable and has a committed drift baseline"
          : `**${unwatched.length}** cited source(s) are UNWATCHABLE — no baseline can be taken or compared, ` +
            `so drift there is undetectable and \`last_verified\` is a human's assertion rather than a checked ` +
            `fact: ` +
            unwatched
              .map((u) => `\`${u}\` (${unwatchableReason(u) === "refuses-our-user-agent" ? "403 to our declared user-agent; we do not spoof one" : "no reviewed drift baseline"})`)
              .join(", "),
      derivedFrom: "`api/watchability.ts` over `corpus/source-hashes.json` + `forms/form-hashes.json` + `corpus/snapshots/index.json`",
    },
    {
      name: "Independently authored expert gold set",
      status: independent ? "DONE" : "OPEN",
      evidence: independent
        ? "the accuracy oracle is independently authored"
        : "`independent_author: false` — the gold set was co-authored with the corpus, so accuracy is partly tautological",
      derivedFrom: "`eval/gold.provenance.json`",
    },
    humanGate("counsel-review", "Counsel review of the disclaimers (UPL)"),
    humanGate("accessibility-walkthrough", "Manual screen-reader / keyboard / 200%-zoom walkthrough"),
    humanGate("bedrock-eval", "Real Bedrock-backed eval run"),
    humanGate("dpia", "DPIA + STRIDE threat-model sign-off"),
  ];
}

export function renderBlock(gates: LaunchGate[]): string {
  const open = gates.filter((g) => g.status === "OPEN").length;
  const lines = [
    START,
    "",
    // Phrasing note: never emit the bare "<N> gates" pattern here — scripts/gate-count.ts
    // scans README.md for exactly that shape to catch a drifted pipeline-stage count, and
    // would read this launch-gate tally as a (wrong) claim about the number of CI stages.
    // Two anti-drift gates, one namespace.
    `**Launch readiness: ${open} of ${gates.length} review gates are OPEN.** Every status below is derived from the`,
    "repository's own artifacts on each `make verify` run — none of it is hand-written, and none of it",
    "can be cleared by editing this table. **No record in this corpus has been verified by a named human.**",
    "",
    "| Launch gate | Status | Machine-derived evidence | Derived from |",
    "|---|---|---|---|",
    ...gates.map(
      (g) => `| ${g.name} | ${g.status === "OPEN" ? "🔴 **OPEN**" : "🟢 DONE"} | ${g.evidence} | ${g.derivedFrom} |`,
    ),
    "",
    END,
  ];
  return lines.join("\n");
}

function main(): void {
  const write = process.argv.includes("--write");
  const block = renderBlock(deriveLaunchGates());
  const mismatches: string[] = [];

  // Test-only override (tests/gate-efficacy), same guarded pattern as the other gates:
  // point the doc-drift check at a fixture tree whose block claims something the artifacts
  // do not support. Unset in production, so behavior is unchanged.
  const docRoot = process.env.LAUNCH_GATES_DOC_ROOT ?? REPO_ROOT;

  for (const target of TARGETS) {
    const path = join(docRoot, target);
    const content = read(path);
    const start = content.indexOf(START);
    const end = content.indexOf(END);
    if (start === -1 || end === -1) {
      mismatches.push(`${target}: no launch-gates block (add the ${START} / ${END} markers)`);
      continue;
    }
    const current = content.slice(start, end + END.length);
    if (current === block) continue;
    if (write) {
      writeFileSync(path, content.slice(0, start) + block + content.slice(end + END.length));
      continue;
    }
    mismatches.push(
      `${target}: the launch-gate block does not match the derived status — run \`make launch-gates-write\``,
    );
  }

  if (mismatches.length > 0) {
    fail("launch-gates", `${mismatches.length} doc(s) drifted from the derived launch-gate status`, mismatches);
  }
  const gates = deriveLaunchGates();
  const open = gates.filter((g) => g.status === "OPEN").length;
  pass(
    "launch-gates",
    write
      ? `launch-gate block regenerated in ${TARGETS.join(", ")} (${open}/${gates.length} OPEN)`
      : `${open}/${gates.length} launch gates OPEN; README + STATUS state the derived truth`,
  );
}

const isMain = process.argv[1] && import.meta.url === `file://${process.argv[1]}`;
if (isMain) main();
